### ISSUE TITLE
之前青龙面板中的环境变量JD_COOKIE可以存在多个，现在怎么只能一个了呢？

### ISSUE THREAD

**Issue by alanzed555** [shufflewzc/faker3#100]
之前青龙面板中的环境变量JD_COOKIE可以存在多个，即：
JD_COOKIE='1111'
JD_COOKIE='2222'
JD_COOKIE='3333'
现在只能是
JD_COOKIE='1111&2222&3333'了，请问这是什么原因呢？
谢谢！

**Comment by shufflewzc** [comment]
目前没发现这个问题 可能是新版问题 建议安装2.11.3
