### ISSUE TITLE
新东东农场幸运抽奖，做了任务，抽不了奖

### ISSUE THREAD

**Issue by winterwd** [shufflewzc/faker3#103]
新东东农场幸运抽奖 | task shufflewzc_faker3_main/jd_XinFarm_draw.js

做了任务，抽不了奖

![image](https://github.com/shufflewzc/faker3/assets/14071671/f0a2f184-1bbc-4203-969f-47323def254d)

**Comment by sylvan99** [comment]
一样的问题 感觉风控变严格了

**Comment by shufflewzc** [comment]
更新库，抽奖脚本单独放了
