### ISSUE TITLE
获取互助码	task shufflewzc_faker3_jd_get_share_code.js  执行会报错

### ISSUE THREAD

**Issue by jkingben** [shufflewzc/faker3#11]
![image](https://user-images.githubusercontent.com/5220242/141926217-e4484513-1b72-4717-8fdf-5a2b23a8fbf8.png)

**Comment by shufflewzc** [comment]
现在试试

**Comment by jkingben** [comment]
一样的错，脚本编辑里，我用github上的整个替换了一遍，再次运行任务，还是这个错
