### ISSUE TITLE
请问如何禁止某个账号不运行价保脚本？

### ISSUE THREAD

**Issue by cuitzeno** [shufflewzc/faker3#110]
配置了如下环境变量，但是好像不起作用。
tempblock_ck_envs_num="1"
tempblock_ck_envs1="jd_OnceApply@-@xxxxxx"

其中xxxxxx是对应的pt_pin值

**Comment by nethawkhu** [comment]
没有例子，我也在找答案。

**Comment by cuitzeno** [comment]
我现在是用的其它脚本，支持通过设置环境变量禁止指定的pin执行任务：
多个任务同pin：BANPIN='任务1|任务2@pin1,pin2'
多个任务不同pin：BANPIN='任务1@pin,pin2&任务2@pin2,pin3'
不指定任务只写pin 全部任务都不执行该pin：BANPIN='pin1,pin2'
