### ISSUE TITLE
领京豆签到失败:异常为: 签到失败,undefined:undefined

### ISSUE THREAD

**Issue by isMc-li** [shufflewzc/faker3#113]
## 开始执行... 2024-07-27 12:37:48

🔔领京豆签到, 开始!

====================共2个京东账号Cookie=================

============脚本执行时间：2024/07/27 12:37:48=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新 关注频道https://t.me/scriptalking>>>>>>>>>>>>>>>

加载sendNotify，当前版本: 20240612
检测到一对一Uid文件WxPusherUid.json，载入...
==========领京豆签到变量开启状态==========
活动入口：APP首页-京东秒杀-签到
间隔时长: [1.5秒]运行间隔时长
代理开关: [关闭]
通知推送: [关闭]
账号过滤: []
==========领京豆签到变量状态结束==========

【账号1】jd**79：签到失败,undefined:undefined
【账号2】jd**7a：签到失败,undefined:undefined

🔔领京豆签到, 结束! 🕛 5.948 秒

## 执行结束... 2024-07-27 12:37:54 耗时 6 秒

**Comment by fivegoone** [comment]
跟你一样的情况 不知道怎么解决

**Comment by shufflewzc** [comment]
已修复

**Comment by isMc-li** [comment]
## 开始执行... 2024-08-01 10:13:47


🔔领京豆签到, 开始!

====================共2个京东账号Cookie=================

============脚本执行时间：2024/08/01 10:13:48=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新 关注频道https://t.me/scriptalking>>>>>>>>>>>>>>>

==========领京豆签到变量开启状态==========
活动入口：APP首页-京东秒杀-签到
间隔时长: [1.5秒]运行间隔时长
代理开关: [关闭]
通知推送: [关闭]
账号过滤: []
==========领京豆签到变量状态结束==========

【账号1】jd**79：签到失败：required string parameter 'functionId' is not present
【账号2】jd**7a：签到失败：required string parameter 'functionId' is not present
