### ISSUE TITLE
大伙有谁遇到过账号莫名其妙的下了游戏点卡的订单不

### ISSUE THREAD

**Issue by subarashiigyoku** [shufflewzc/faker3#122]
大伙有谁遇到过，半夜自动下单的问题不，不知道哪个脚本引起的。挂的几个号，有部分号都有这个订单, 还成功了，然后被删除了订单了，询问客服后台看到是删除了
![image](https://github.com/user-attachments/assets/741090d8-dc06-4f1f-b45a-43d8ed8ad70a)

**Comment by maskcse** [comment]
遇到过。但是查不到用哪个微信支付的

**Comment by Mydong** [comment]
遇到了就是因为这个才上来找原因的
我一共就挂了两个脚本
这个问题在另外一个作者的脚本库里面
也有人反馈

**Comment by subarashiigyoku** [comment]
> 遇到了就是因为这个才上来找原因的 我一共就挂了两个脚本 这个问题在另外一个作者的脚本库里面 也有人反馈

具体是哪个脚本或者是哪个原作者的脚本您有知道不

**Comment by shufflewzc** [comment]
目前问题已解决！但是究竟是哪个漏洞不得而知
