### ISSUE TITLE
惊喜牧场BUG

### ISSUE THREAD

**Issue by a4081675** [shufflewzc/faker3#13]
root@qinglong:/ql $ ls -l repo/shufflewzc_faker3_main/jd_jxmc.js
-rw-r--r-- 1 root root 126034 Aug 10 13:45 repo/shufflewzc_faker3_main/jd_jxmc.js
root@qinglong:/ql $ ls -l scripts/shufflewzc_faker3_main/jd_jxmc.js
-rw-r--r-- 1 root root 77247 Aug 10 13:46 scripts/shufflewzc_faker3_main/jd_jxmc.js

更新库会导致jd_jxmc.js被截断。里面内容少了很多，导致脚本无法执行。大佬能否看看是因为啥？

**Comment by shufflewzc** [comment]
已修复了
