### ISSUE TITLE
今天大更新，青龙任务添加失败

### ISSUE THREAD

**Issue by wingswing1** [shufflewzc/faker3#15]
shufflewzc_faker3 新增任务

jd_work_price.js -> 添加失败(Constraint error, got value 27 expected range 0-23)
全民抢京豆 -> 添加失败(Constraint error, got value 27 expected range 0-23)
东东世界兑换 -> 添加失败(Constraint error, got value 27 expected range 0-23)
jd_work_validate.js -> 添加失败(Constraint error, got value 27 expected range 0-23)
加购物车抽奖 -> 添加失败(Constraint error, got value 27 expected range 0-23)
批量取关店铺和商品 -> 添加失败(Constraint error, got value 27 expected range 0-23)
特务Z -> 添加失败(Constraint error, got value 27 expected range 0-23)
大牌联合 -> 添加失败(Constraint error, got value 27 expected range 0-23)

本通知 By ccwav Mod
通知时间: 2021-11-20 12:34:41

**Comment by shufflewzc** [comment]
这是青龙版本的问题？？

**Comment by wingswing1** [comment]
> 这是青龙版本的问题？？

破案了 是定时文件设置错误 和脚本无关
