### ISSUE TITLE
金融养猪今天开始任务完成不推送了

### ISSUE THREAD

**Issue by lxr760** [shufflewzc/faker3#16]
脚本jd_pigPet.js

之前任务完成会提醒，今天开始不提醒了。看日志里，直接没有调用推送的部分。

**Comment by shufflewzc** [comment]
好像更新的脚本去掉了，我再看看有没有带通知版本的

**Comment by lxr760** [comment]
> 

代码https://github.com/shufflewzc/faker3/blob/main/jd_pigPet.js里   最后一行能看到系统通知的字样，不知道是代码bug 还是什么原因 ，任务跑完以后，实际是不推送的
