### ISSUE TITLE
为什么很多定时任务的时间都是7 7 7 7 7或1 1 1 1 1 ？

### ISSUE THREAD

**Issue by tingyue-wu** [shufflewzc/faker3#19]
为什么很多定时任务的时间都是7 7 7 7 7或1 1 1 1 1 ？
有的可能需要手动运行，不是每天必须，但是现在这样的脚本也太多了。
占了脚本库的一半。faker2库里的这些脚本，定时也是这样吗？

**Comment by shufflewzc** [comment]
这是spy监控脚本 详情可以进频道看
