### ISSUE TITLE
初始化农场数据异常, 请登录京东 app查看农场0元水果功能是否正常。

### ISSUE THREAD

**Issue by manBoooooooooooooom** [shufflewzc/faker3#24]
大佬 请问下我有一些账号跑农场会出现这个错误。
我看了下脚本 是用户信息读取异常。但是这个游戏我在手机上是没有问题的。请问该怎么处理？

**Comment by hongyings** [comment]
是报这个"**getaddrinfo EAI_AGAIN**"错吗？这个看下登陆日志，显示IP为空且登陆地址获取失败
猜测这个可能跟IP有关，**我用的是虚拟机**，解决方式如下：
1.管理员方式登陆cmd
2.重置网络跟IP（命令如下）,重启电脑即可
`1. netsh winsock reset
 2. netsh int ip reset all`

**Comment by manBoooooooooooooom** [comment]
> 

有好几个账号 只有一个可以正常执行任务，我并不是使用的虚拟机。我看看有没有其他办法可以重置一下网络信息

**Comment by hongyings** [comment]
你这种还能执行一个号情况没遇到过，试试别的方式吧

**Comment by Aphelion-star** [comment]
我也有这个问题
