### ISSUE TITLE
使用spy会导致封号吗？

### ISSUE THREAD

**Issue by Always67** [shufflewzc/faker3#33]
首先自用的tg被封了，又注册了两个小号都被封了，不知道是哪里姿势不对。还是说新号不能用api。
配置如下：
Telegram:
  Log_En: true
  TgLost: ''
  Welcome: 亲爱的,我来啦~~
  api_hash: 212474a82ecd75b8c3291550f8280c1e
  api_id: 29274606
  forward_channel_id: ''
  forward_keyword: []
  forward_user_id: []
  forward_user_name: []
  listen_CH:
  - -1001670294604
  log_id: -822896050
  master_id:
  - 5525326095
  mtproto: ''
  proxy_http: ''
  proxy_ip: ''
  proxy_password: ''
  proxy_port: 11223
  proxy_type: ''
  proxy_username: ''
Use_SillyGirl: false
WaitTime: 10
authtype: new
auto_backup: true
auto_backup_size: 5000
blackList: []
branch: master
down_proxy: ''
js_config:
- Container:
  - []
  Env: jd_cjzd
  KeyWord:
  - - 频道1变量A1
  - - 频道2变量A2
  Name: cj组队
  Script: jd_team60.js
  TimeOut: 0
  Wait: 3
logmode: 0
rss_urls:
  Faker: https://github.com/shufflewzc/AutoSpy/raw/master/config/Faker.spy
update_url: https://raw.githubusercontent.com/xieshang/AutoSpy/master/updatelist.json

**Comment by ParentChain** [comment]
老号也不行 我5年老号挂了

**Comment by YDuck-JNU** [comment]
同样，用的GV老号，按教程第一次登录就马上Banned了，等了四五个月才解，心不死，再试一次，马上又封，是不是得+86才行的？？？
