### ISSUE TITLE
shufflewzc大佬，请教您一个问题（关于nodejs和python的）

### ISSUE THREAD

**Issue by hellooldtimes** [shufflewzc/faker3#36]
因为自己有c，java，JavaScript和python基础，想自己也学大佬的JD库写一个duoduo牧场的。但是我研究了一下，为什么现在很多脚本都是nodejs写的，很少python？nodejs写这类脚本比python有哪些优势呢？求大佬指点

**Comment by kalvinses** [comment]
多多你也敢刷，分分钟黑号吧
