### ISSUE TITLE
拉库命令

### ISSUE THREAD

**Issue by ROOOCCCK** [shufflewzc/faker3#4]
求最新拉库命令

**Comment by popsee** [comment]
ql repo https://github.com/shufflewzc/faker3.git "jd_|jx_|gua_|jddj_|getJDCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_Pure|sign_graphics_validate|ql" "main"

**Comment by shufflewzc** [comment]
进群找吧
