### ISSUE TITLE
消息推送频繁

### ISSUE THREAD

**Issue by zhf883680** [shufflewzc/faker3#45]
脚本禁用重复任务的消息推送太频繁了吧   
修改推送  但又因为更新库的原因 代码又回滚了 有什么处理办法吗  直接禁用任务吗

**Comment by rendaa** [comment]
同问。
而且脚本禁用通知好像是只要有被禁用的脚本，即使没有新变化，也是每次定时任务都会发送。
希望考虑添加一个简单的消息订阅管理，只及时推送自己关心的消息，不很关心的可以弄个按设定的周期一起发送。
