### ISSUE TITLE
脚本拉取失败

### ISSUE THREAD

**Issue by realcxj1989** [shufflewzc/faker3#50]
![image](https://user-images.githubusercontent.com/28385710/150094157-1104b9cc-bb94-4bdf-975a-624429cb2a63.png)

**Comment by ZhengchaoCao** [comment]
同上，，无论怎么弄都是，网络失败

**Comment by chaoscaros** [comment]
把青龙配置文件里差不多20行的GithubProxyUrl=“****”的注释掉就行了

**Comment by ZhengchaoCao** [comment]
具体哪个路径呀！

**Comment by ZhengchaoCao** [comment]
> 把青龙配置文件里差不多20行的GithubProxyUrl=“****”的注释掉就行了

具体在哪里修改，，教下大佬
