### ISSUE TITLE
请问"领京豆签到"是挂了吗？

### ISSUE THREAD

**Issue by dover** [shufflewzc/faker3#56]
之前都能正常签到，这几天突然就报错了。。。。

![jd_beanSign](https://github.com/shufflewzc/faker3/assets/8148653/4022d3cc-beef-4534-9647-d335c7aec8cb)

**Comment by Marblog** [comment]
缺少ds依赖呀，装一下

**Comment by Marblog** [comment]
> 之前都能正常签到，这几天突然就报错了。。。。
> 
> ![jd_beanSign](https://user-images.githubusercontent.com/8148653/266037164-4022d3cc-beef-4534-9647-d335c7aec8cb.png)
缺少ds依赖呀，装一下

**Comment by dover** [comment]
> > 之前都能正常签到，这几天突然就报错了。。。。
> > ![jd_beanSign](https://user-images.githubusercontent.com/8148653/266037164-4022d3cc-beef-4534-9647-d335c7aec8cb.png)
> > 缺少ds依赖呀，装一下

非常感谢指导
