### ISSUE TITLE
种豆得豆运行到第三个帐号会有异常

### ISSUE THREAD

**Issue by yejun0201** [shufflewzc/faker3#6]
种豆得豆运行到第三个帐号会有异常：
(node:5595) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at /ql/scripts/shufflewzc_faker3_jd_plantBean.js:572:45
    at new Promise (<anonymous>)
    at shareCodesFormat (/ql/scripts/shufflewzc_faker3_jd_plantBean.js:564:10)
    at /ql/scripts/shufflewzc_faker3_jd_plantBean.js:71:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by red1412** [comment]
禁用三个账号试试

**Comment by shufflewzc** [comment]
应该是ck的问题
