### ISSUE TITLE
现在京东cooki只有三天有效么？

### ISSUE THREAD

**Issue by tsiens** [shufflewzc/faker3#67]
家里三个帐号，两个手机验证码登录，一个帐号密码登录，都是两三天就过期。。

**Comment by tycn888** [comment]
用wskey，可以持续半年。

**Comment by shufflewzc** [comment]
@tycn888 谁跟你说的。。

**Comment by lxmicode** [comment]
确保获取cookie的时候，跟常住地一样地区

**Comment by guanchen-super** [comment]
是的  都是两三天就失效了

**Comment by dong50252409** [comment]
转wskey可以持续多久 @shufflewzc

**Comment by guanchen-super** [comment]
亲测  转wskey 有效期四天

**Comment by tycn888** [comment]
2023/11/21 21：00 更新的cookie 到现在差不多6天了还没过期呢，京东域名分流走本地线路。

**Comment by JmsWang** [comment]
> 2023/11/21 21：00 更新的cookie 到现在差不多6天了还没过期呢，京东域名分流走本地线路。

走本地线路，这怎么操作的

**Comment by tycn888** [comment]
> > 2023/11/21 21：00 更新的cookie 到现在差不多6天了还没过期呢，京东域名分流走本地线路。
> 
> 走本地线路，这怎么操作的

方法很多啊，
我的思路是：
passwall分流，京东域名直连，
京东域名github有，
smartdns用国内DNS服务器解析直连域名。
chrome无痕模式账号登录后，用浏览器获得cookie，这次cookie有效期为7天。

**Comment by guanchen-super** [comment]
> > > 2023/11/21 21：00 更新的cookie 到现在差不多6天了还没过期呢，京东域名分流走本地线路。
> > 
> > 
> > 走本地线路，这怎么操作的
> 
> 方法很多啊， 我的思路是： passwall分流，京东域名直连， 京东域名github有， smartdns用国内DNS服务器解析直连域名。 chrome无痕模式账号登录后，用浏览器获得cookie，这次cookie有效期为7天。

大佬  我查了一下 passwall 还需要路由器上支持  对于新手来说  我这个  有点困难了

**Comment by guanchen-super** [comment]
> 用wskey，可以持续半年。

麻烦问一下  持续半年是怎样操作的  我这边使用wskey 也就四五天左右  然后wskey就失效了

**Comment by 327078466** [comment]
虚心求教 为啥现在抓cookie 没有wskey啦

**Comment by shufflewzc** [comment]
@327078466 由于安全策略影响，都是3天，建议安装rabbit让登录更方便
