### ISSUE TITLE
资产推送未走企业微信代理地址

### ISSUE THREAD

**Issue by thsrite** [shufflewzc/faker3#79]
`青龙配置的企业微信应用通知`

执行资产推送的日志如下，`发送失败`提示`当前ip没配置在企业微信应用的可信ip`。
由于家宽ip不固定，所以`采用企业微信代理地址`进行消息推送。
然而`资产推送没走企业微信代理地址未成功推送消息`，但是执行`ql repo https://git.metauniverse-cn.com/https://github.com/shufflewzc/faker3.git "jd_|jx_|gua_|jddj_|jdCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_|sign_graphics_validate|ql|JDSignValidator|magic|depend|h5sts" "main"`  
`新增任务走了企业微信代理地址并正确推送了消息`。

## 开始执行... 2023-12-26 14:18:39

🔔京东资产统计, 开始!

====================共1个京东账号Cookie=================

============脚本执行时间：2023/12/26 14:18:40=============

>>>>>>>>>>>>>>Faker提醒您：有问题先更新不行在反馈>>>>>>>>>>>>>>>

检测到资产变动缓存文件2023-12-26.json，载入...
检测到资产变动缓存文件2023-12-26.json，载入...
******开始查询【京东账号1】jd_7bce*********
领现金查询失败，服务器没有返回具体值.
【账号1🆔】***(已实名)
【账号信息】Plus会员(105分),京享值6667
【京豆变动】0豆(与今日14:15比较)
【当前京豆】275豆(≈2.75元)
【东东农场】6枚皮蛋(92%)
【话费积分】1.48(最近已过期:3/4)
🧧🧧🧧红包明细🧧🧧🧧
【红包总额】0.00(总过期0.00)元 

添加缓存2023-12-26.json成功!
not allow to access from your ip, hint: [1703571524252851254021128], from ip: 119.*.*.*, more info at https://open.work.weixin.qq.com/devtool/query?e=60020

🔔京东资产统计, 结束! 🕛 14.029 秒

## 执行结束... 2023-12-26 14:18:54  耗时 15 秒　　　　　

`青龙配置文件和通知配置均已配置微信应用代理地址`
![image](https://github.com/shufflewzc/faker3/assets/54088512/525aa748-dedb-4010-9e38-d3dd63634fd5)
![image](https://github.com/shufflewzc/faker3/assets/54088512/3b994535-f186-4959-946a-f4a2c2e48370)
`且可收到测试的消息和拉库增加脚本的消息`
![image](https://github.com/shufflewzc/faker3/assets/54088512/58e9d3ca-ae86-45d3-8411-97fc1f6318b8)

**Comment by thsrite** [comment]
青龙及faker3脚本均已最新

**Comment by shufflewzc** [comment]
资产推送脚本建议配置wxpusher，可一对一通知
