### ISSUE TITLE
怎么现在又开始搞那些乱七八糟的加密的脚本？能不能删掉

### ISSUE THREAD

**Issue by gimgoo** [shufflewzc/faker3#8]
如题，怎么现在又开始搞那些乱七八糟的加密的脚本？能不能删掉。加密的脚本都不知道那些作者干什么亏心事一样还不敢让人看代码，真要抄或者干嘛的肯定会刻意破解，加密也没用。而大部分人只是拉来用的，看到加密的放心都不放心。

**Comment by shufflewzc** [comment]
哪些啊？

**Comment by gimgoo** [comment]
jd_dfw.js      jd_dadoudou.js  这两个都是，具体有多少个是加密的我不清楚，这两个最近添加的我刚好看了下。

**Comment by gimgoo** [comment]
采集归采集，加密的就别搞进来了。讲真
