### ISSUE TITLE
京东多合一签到异常，缺少模块

### ISSUE THREAD

**Issue by jkingben** [shufflewzc/faker3#8]
![image](https://user-images.githubusercontent.com/5220242/141404627-d815cb67-00c7-4abe-901f-171922039eb0.png)

**Comment by jiangbeth** [comment]
如何助力呢

**Comment by zoverdoser** [comment]
遇到相同的问题

**Comment by drw2005** [comment]
> 遇到相同的问题 在容器里执行npm install png-js就好了

也遇到这个问题了，执行npm install png-js出现错误，还是不行。
哪位大佬有解决办法？

**Comment by shufflewzc** [comment]
在我教程里找一键安装依赖脚本执行一下
