### ISSUE TITLE
【bug】东东农场指定助力jd_fruit_zdhelp.js 无法设置为指定助力码

### ISSUE THREAD

**Issue by lxr760** [shufflewzc/faker3#80]
该脚本内的助力说明为：
下方变量 二选一：
设置助力账号变量：export jd_fruit_help_pin='pin值' 定义助力账号，多个用 & 隔开
设置助力码变量：export jd_fruit_help_code='code值' 定义助力码，多个助力码用 @ 连接或者 | 连接 或者 & 连接

但是我只设置了export jd_fruit_help_code='code值'         
运行脚本还是会提示   “检测到环境变量同时存在指定账号变量和指定助力码变量，请调整后运行”

然后我只设置了export jd_fruit_help_code并没有设置export jd_fruit_help_pin='pin值'      脚本是不是有bug

**Comment by shufflewzc** [comment]
收到 我检查下
