### ISSUE TITLE
Error: Cannot find module './function/dylanz'

### ISSUE THREAD

**Issue by karmas056** [shufflewzc/faker3#81]
Error: Cannot find module './function/dylanz'
这种报错怎么解决啊，找不到模块，是我代码没拉完吗？
ql repo https://git.metauniverse-cn.com/https://github.com/shufflewzc/faker3.git
有没有博客解释过这种情况，求告知~

**Comment by shufflewzc** [comment]
@chenkui-it 是的，建议用2.11.3版本青龙拉库

**Comment by karmas056** [comment]
> @chenkui-it是的，建议用2.11.3版本青龙拉库

我是 2.10.13，意思我要删除docker重新拉取是吧；

**Comment by shufflewzc** [comment]
@chenkui-it 这个版本不需要换，你拉库命令应该不对，重新拉一下

**Comment by karmas056** [comment]
> @chenkui-it 这个版本不需要换，你拉库命令应该不对，重新拉一下

ql repo https://git.metauniverse-cn.com/https://github.com/shufflewzc/faker3.git
这不对？
能发下对的吗？感谢!!!

**Comment by shufflewzc** [comment]
@chenkui-it 看Readme

**Comment by karmas056** [comment]
> @chenkui-it 看Readme

ql repo https://git.metauniverse-cn.com/https://github.com/shufflewzc/faker3.git "jd_|jx_|gua_|jddj_|jdCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_|sign_graphics_validate|ql|JDSignValidator|magic|depend|h5sts" "main"

是这个吗？
教程的说明，跟我的不太一样，我自己安装了docker，只要拉库就行了；然后这个拉库的命令怎么看怎么不对；就自己弄了拉库的命令；

**Comment by karmas056** [comment]
> @chenkui-it 看Readme

重新拉库 需要清空 本地所有脚本吗：

ql repo https://git.metauniverse-cn.com/https://github.com/shufflewzc/faker3.git "jd_|jx_|gua_|jddj_|jdCookie" "activity|backUp" "^jd[^_]|USER|function|utils|sendNotify|ZooFaker_Necklace.js|JDJRValidator_|sign_graphics_validate|ql|JDSignValidator|magic|depend|h5sts" "main"

我用这个 拉完了；

**Comment by karmas056** [comment]
> @chenkui-it 看Readme

//以下代码下载2.11.3版本青龙

wget -q https://yanyu.ltd/https://raw.githubusercontent.com/yanyuwangluo/VIP/main/Scripts/sh/ql.sh -O ql.sh && bash ql.sh

//以下代码下载2.12版本青龙

wget -q https://yanyu.ltd/https://raw.githubusercontent.com/yanyuwangluo/VIP/main/Scripts/sh/ql12.sh -O ql12.sh && bash ql12.sh


这两个命令 拉下来的文件都是空的；ql.sh   ql12.sh

**Comment by shufflewzc** [comment]
> > @chenkui-it 看Readme
> 
> //以下代码下载2.11.3版本青龙
> 
> wget -q https://yanyu.ltd/https://raw.githubusercontent.com/yanyuwangluo/VIP/main/Scripts/sh/ql.sh -O ql.sh && bash ql.sh
> 
> //以下代码下载2.12版本青龙
> 
> wget -q https://yanyu.ltd/https://raw.githubusercontent.com/yanyuwangluo/VIP/main/Scripts/sh/ql12.sh -O ql12.sh && bash ql12.sh
> 
> 这两个命令 拉下来的文件都是空的；ql.sh ql12.sh

网络不好,可以去掉代理直接拉

**Comment by karmas056** [comment]
问题解决了；直接拉代码到服务器；复制文件夹到容器：

git clone https://github.com/shufflewzc/faker3.git

docker cp /opt/qinglong/faker3/function  qinglong:/ql/data/scripts/shufflewzc_faker3/

docker cp /opt/qinglong/faker3/icon  qinglong:/ql/data/scripts/shufflewzc_faker3/

docker cp /opt/qinglong/faker3/utils  qinglong:/ql/data/scripts/shufflewzc_faker3/

**Comment by shufflewzc** [comment]
@chenkui-it 也是解决方法之一
