### ISSUE TITLE
数据备份

### ISSUE THREAD

**Issue by karmas056** [shufflewzc/faker3#82]
系统设置 -》其他设置 -》 数据备份还原
想问这个备份还原的功能是否能实现：
禁用了的脚本，重新拉库部署后导导入这个备份数据，之前禁用的任务，依然是禁用状态，

备份了那些东西；还原时能恢复哪些东西；

**Comment by shufflewzc** [comment]
@chenkui-it 建议自己备份env文件就好 其他的不需要备份

**Comment by karmas056** [comment]
> @chenkui-it 建议自己备份env文件就好 其他的不需要备份

这个 env 在什么地方；麻烦给绝对路径；任务里面只有一个jd_env，我想应该不是这个；
拜托~

**Comment by shufflewzc** [comment]
@chenkui-it root，qinglong config里面

**Comment by chenkui-it** [comment]
我想着你说的位置应该是在容器中：
root@qinglong:/ql $ ls
LICENSE       README.md  cli     data  docker               jbot  node_modules  package.json    raw   sample   shell  static              tsconfig.json  version.yaml
README-en.md  back       config  db    ecosystem.config.js  log   nodemon.json  pnpm-lock.yaml  repo  scripts  src    tsconfig.back.json  typings.d.ts
root@qinglong:/ql $ 
root@qinglong:/ql $ cd config/
root@qinglong:/ql/config $ 
root@qinglong:/ql/config $ 

但是他是空的；拜托~

**Comment by karmas056** [comment]
> @chenkui-it root，qinglong config里面

我想着你说的位置应该是在容器中：
root@qinglong:/ql $ ls
LICENSE README.md cli data docker jbot node_modules package.json raw sample shell static tsconfig.json version.yaml
README-en.md back config db ecosystem.config.js log nodemon.json pnpm-lock.yaml repo scripts src tsconfig.back.json typings.d.ts
root@qinglong:/ql $
root@qinglong:/ql $ cd config/
root@qinglong:/ql/config $
root@qinglong:/ql/config $

但是他是空的；拜托~

**Comment by shufflewzc** [comment]
@chenkui-it 在文件目录

**Comment by karmas056** [comment]
> @chenkui-it 在文件目录

容器里面还是服务器里面，找到了.env但是好像不是的；具体路径是啥；大佬

**Comment by shufflewzc** [comment]
@chenkui-it 服务器

**Comment by shufflewzc** [comment]
@chenkui-it 你进tg群里来问吧

**Comment by karmas056** [comment]
> @chenkui-it 你进tg群里来问吧

需要一个TG链接，谢谢诶；
