### ISSUE TITLE
更新后报错 Update jd_bean_change.js

### ISSUE THREAD

**Issue by bokelife** [shufflewzc/faker3#84]
最新版本一直报错，还原上一个版本就不会报错，第二天又自动更新了继续报错
![截图_20240118025116](https://github.com/shufflewzc/faker3/assets/8927565/63e03738-c821-4b2f-ae92-ccd0097d8afc)

**Comment by shufflewzc** [comment]
@bokelife 依赖装重复了把

**Comment by bokelife** [comment]
> @bokelife 依赖装重复了把

请问是什么依赖重复了，我查看了好像没重复的。在上一个版本的可以正常运行，最新这个版本的就会报错
