### ISSUE TITLE
wskey转换成功，但是在账号启用禁用接口失败

### ISSUE THREAD

**Issue by Jesn** [shufflewzc/faker3#85]
青龙面板 [v2.10.13]

![image](https://github.com/shufflewzc/faker3/assets/5728274/07369f0a-ad36-425d-877b-a987fb440f58)

**Comment by shufflewzc** [comment]
@Jesn 最近出现的还是以前就这样

**Comment by Jesn** [comment]
> @Jesn 最近出现的还是以前就这样

之前的日志删除了，不太清楚什么时候开始的

**Comment by Jesn** [comment]
更新到最新版本后就好了
