### ISSUE TITLE
新农场任务 转盘出错

### ISSUE THREAD

**Issue by bondlazy** [shufflewzc/faker3#93]
task shufflewzc_faker3_main/jd_fruit_new.js

东东农场: API请求失败 ‼️‼️
"Response code 403 (Forbidden)"
function_id:wheelsHome

❗️新农场任务, 错误!

初始化天天抽奖得好礼失败！
执行继续浇水...
检查剩余水滴能否继续浇水...

**Comment by shufflewzc** [comment]
@bondlazy 解决中

**Comment by bondlazy** [comment]
更新脚本后出现下面错误了:

******开始【京东账号2】jd_57e******

❌ 脚本运行遇到了错误
TypeError: common[_0x4759f4(...)] is not a function

🔔新东东农场任务, 结束! 🕛 8.943 秒

**Comment by shufflewzc** [comment]
@bondlazy 再更新一下即可

**Comment by winterwd** [comment]
做了任务，抽不了奖

![image](https://github.com/shufflewzc/faker3/assets/14071671/f0a2f184-1bbc-4203-969f-47323def254d)
