### ISSUE TITLE
欢乐淘金（发财挖宝）任务 报错

### ISSUE THREAD

**Issue by hojihua** [shufflewzc/faker3#94]
欢乐淘金（发财挖宝）任务  jd_fcwb_auto.js
这个报错是少什么依赖吗？

。。。。。。。。。

******开始【京东账号31】35******

🚫 happyDigHome 请求失败 ➜ error:1426E0B9:SSL routines:ciphersuite_cb:no cipher match
🙅‍♂ 未能正确获取到主页信息，退出执行！

******开始【京东账号32】pMLS******

🚫 happyDigHome 请求失败 ➜ error:1426E0B9:SSL routines:ciphersuite_cb:no cipher match
🙅‍♂ 未能正确获取到主页信息，退出执行！

******开始【京东账号33】fqBVY******

🚫 happyDigHome 请求失败 ➜ error:1426E0B9:SSL routines:ciphersuite_cb:no cipher match
🙅‍♂ 未能正确获取到主页信息，退出执行！

**Comment by shufflewzc** [comment]
@hojihua 你的网络环境可能无法适配

**Comment by hojihua** [comment]
那有没有另外的方法解决呢，是网络IP被限制了吗，还是SSL证书问题呢
