### ISSUE TITLE
活动id获取问题

### ISSUE THREAD

**Issue by gz2021** [shufflewzc/faker3#95]
这些环境变量需要的活动怎么获取啊

       jd_wxSign_sign_lzkj_Ids // 超级无线签到有礼活动id，多个用英文逗号分割
        jd_wxSign_sevenDay_lzkj_Ids // 超级无线7日签到活动id，多个用英文逗号分割
        jd_wxSign_sign_cjhy_Ids // 超级会员签到有礼活动id，多个用英文逗号分割
        jd_wxSign_sevenDay_cjhy_Ids // 超级会员7日签到活动id，多个用英文逗号分割

**Comment by shufflewzc** [comment]
@gz2021 进我频道 有线报频道教程
