### ISSUE TITLE
新东东农场任务的浇次数怎么修改

### ISSUE THREAD

**Issue by tianwufeng** [shufflewzc/faker3#98]
jd_XinFarm_waternum // 浇水次数，默认 10次

('jd_XinFarm_waternum\x20//\x20浇水次数，默认\x2010次')

这个怎么修改才是浇水1000

**Comment by shufflewzc** [comment]
@tianwufeng 100

**Comment by tianwufeng** [comment]
jd_XinFarm_waternum 1000 // 浇水次数，默认 10次
这样不行啊
浇水1000次

**Comment by bohu-t** [comment]
在青龙配置文件最下面加一行这个然后保存 export jd_XinFarm_waternum="1000"
